canciones_favoritas = [
    "Par Amar - Los Prisioneros", 
    "Una nube cuelga sobre mi - Los Bunkers", 
    "La Lisa - Lisa", 
    "Milagrosa - Milo J", 
    "Ven aquí - Los Bunkers", 
    "Dimeloma - Marcianeke", 
    "El Baile De Los Que Sobran - Los Prisioneros", 
    "No Me Hables De Sufrir - Los Bunkers", 
    "Mientes - Los Bunkers", 
    "1977 - Ana Tijoux", 
    "Tu Amor - Mon Laferte", 
    "El Duelo - La Ley", 
    "La Espada & La Pared - Los Tres", 
    "En El Río - Vitaa", 
    "Te Recuerdo - Gepe", 
    "Ven - Dënver", 
    "Vuelvo - Fito Páez & Mon Laferte", 
    "La Vela Puerca - El Rey Del Falsete", 
    "Eres - Nicole", 
    "Eres - Café Tacvba", 
    "El Lamento Del Rey - Pedropiedra", 
    "El Último Tren - Pánico", 
    "El Juego Sucio - Tiro De Gracia", 
    "Milagrosa - Milo J", 
    "Aguas profundas - Los Bunkers", 
    "Una Nube Cuelga Sobre Mi - Los Bunkers", 
    "Estrechez De Corazón - Los Prisioneros", 
    "Peces - Ana Tijoux", 
    "Te Reto - Francisca Valenzuela", 
    "La Noche - Cami", 
    "Tus Amigos - Fondo De Bikini", 
    "Pateando Piedras - Los Prisioneros", 
    "La Sombra - Pedropiedra", 
    "Tómame - Francisca Valenzuela", 
    "De Solo Escucharla - Cerveza", 
    "La Primera Vez - Los Tres", 
    "Eso Es El Amor - Javiera Mena", 
    "Mírame - Moral Distraída", 
    "La Cumbia de los Trapos - Los Auténticos Decadentes", 
    "Mi Agüita Amarilla - Los Toreros Muertos", 
    "Rayando El Sol - Maná", 
    "La Negra Tomasa - Caifanes", 
    "El Baile y El Salón - Café Tacvba", 
    "Mis Planes Son Amarte - Juanes", 
    "Limón Y Sal - Julieta Venegas", 
    "La Ingrata - Café Tacvba", 
    "El Canto de la Sirena - Tierra Santa", 
    "Me Gusta Como Eres - Jarabe de Palo", 
    "El Perdón - Nicky Jam", 
    "Nunca Voy A Olvidarte - La India", 
    "Despacito - Luis Fonsi", 
    "Vivir Lo Nuestro - Marc Anthony & La India", 
    "Querida - Juan Gabriel", 
    "Soy Yo - Bomba Estéreo", 
    "La Camisa Negra - Juanes", 
    "Alicia - Bunbury", 
    "Los Auténticos - Vicentico", 
    "Frijolero - Molotov", 
    "Vivir Lo Nuestro - La India", 
    "Casi Te Envidio - El Puma", 
    "Mi Gente - J Balvin", 
    "Casi Te Envidio - La India", 
    "El Baile y El Salón - Café Tacvba", 
    "Eres - Café Tacvba", 
    "Limón y Sal - Julieta Venegas", 
    "Casi Te Envidio - La India", 
    "Baila Esta Cumbia - Selena", 
    "La Cumbia Del Sol - La Sonora Carruseles", 
    "Me Enamora - Juanes", 
    "Vuelvo - Fito Paez", 
    "El Carretero - Vicente Fernández", 
    "El Cantante - Rubén Blades", 
    "Soy Yo - Bomba Estéreo", 
    "La Bicicleta - Carlos Vives & Shakira", 
    "Pa' Que Retozen - Tego Calderón", 
    "Magalenha - Sergio Mendes", 
    "La Loba - Shakira", 
    "Nunca Es Suficiente - Natalia Lafourcade", 
    "Mujeres - Ricardo Arjona", 
    "Los Auténticos Decadentes - La Cumbia De Los Trapos", 
    "Gimme The Power - Molotov", 
    "Amor Eterno - Rocío Dúrcal", 
    "Quiero Ser - Amaury Pérez", 
    "René - Residente", 
    "Ojalá - Silvio Rodríguez", 
    "Mujeres - Ricardo Arjona", 
    "Me Gusta Como Eres - Jarabe de Palo", 
    "Me Enamora - Juanes", 
    "Limón Y Sal - Julieta Venegas", 
    "El Son De La Negra - Vicente Fernández", "Lala - Lolo"
]

canciones_favoritas.append("Congelao - Cachureos")
canciones_favoritas.append("Mi gran noche - Rafael")

canciones_favoritas.pop() #Elimino mi gran noche
canciones_favoritas.pop() #Congelao
canciones_favoritas.pop() #ala Lolo
canciones_favoritas.pop() #EL son de la negra



contador = 0
for cancion in canciones_favoritas :
    print(f"El nombre de la cancion {contador} es: {cancion} ")
    contador = contador + 1
