CATALOGO_REFERENCIA = {
    # Acción
    "AC-01": "Duro de Matar",
    "AC-02": "Mad Max: Furia en el Camino",
    "AC-03": "John Wick",
    "AC-04": "Misión Imposible: Sentencia Mortal",
    "AC-05": "Terminator 2: El Juicio Final",
    "AC-06": "Gladiador",
    "AC-07": "Los Vengadores",
    "AC-08": "300",
    "AC-09": "Speed: Máxima Potencia",
    "AC-10": "El Caballero de la Noche",
    "AC-11": "Kill Bill Vol. 1",
    "AC-12": "Rápidos y Furiosos 5",
    "AC-13": "Top Gun: Maverick",
    "AC-14": "Matrix",
    "AC-15": "Heat: Fuego contra Fuego",
 
    # Terror
    "TE-01": "El Exorcista",
    "TE-02": "Hereditary",
    "TE-03": "La Cosa",
    "TE-04": "El Resplandor",
    "TE-05": "Get Out",
    "TE-06": "Halloween",
    "TE-07": "It: Eso",
    "TE-08": "La Conjuración",
    "TE-09": "Midsommar",
    "TE-10": "Alien: El Octavo Pasajero",
    "TE-11": "Insidious",
    "TE-12": "Saw",
    "TE-13": "Náufrago... digo, El Aro",
    "TE-14": "Terrifier 2",
    "TE-15": "La Bruja",
 
    # Animación
    "AN-01": "Toy Story",
    "AN-02": "Spider-Man: Un Nuevo Universo",
    "AN-03": "El Viaje de Chihiro",
    "AN-04": "Up",
    "AN-05": "Coco",
    "AN-06": "Shrek",
    "AN-07": "WALL-E",
    "AN-08": "Zootopia",
    "AN-09": "Tu Nombre",
    "AN-10": "Cómo Entrenar a tu Dragón",
    "AN-11": "Inside Out",
    "AN-12": "El Increíble Hulk... no, Los Increíbles",
    "AN-13": "Ratatouille",
    "AN-14": "Akira",
    "AN-15": "El Viaje de Marona",
}

