print("hola mundo 1")
print("hola mundo 2")
print("hola mundo 3")
print("hola mundo 4")
print("madre mia wily")
print("hola yutu")
print("sale ")
print("Clove no me mola bro ")
print("Bro aguante yuumi top full ad")
print("ME lo a metido vegettaaaa")
