def intentar_aumentar(numero):
    numero += 10
x = 5
intentar_aumentar(x)
print(x)            #IMPRIME 5 YA QUE EL VALOR DE X QUEDO ENCAPSULADA EN LA FUNCION, AL NO RETORNAR NADA MANTIENE SU VALOR ORIGINAL.
#DATOS MUTABLES = LISTAS, DICCIONARIOS, CONJUNTOS(set)  | DATOS INMUTABLES = INT, FLOAT, BOOL, TUPLE